### ISSUE TITLE
Empty array being returned just for my username

### ISSUE THREAD

**Issue by Daryan97** [arifszn/blog.js#62]
Hi,
I been having this issue with blog.js when I try to call this:
```
getDevPost({
  user: 'daryan',
}).then((res) => {
  console.log(res);
});
```

It returns an empty array. when I check the API call, everything seems fine.
I have tried different usernames for my account but the result is still the same, and I have tried other people's username and it works just fine with their username.

**Additional note:** I have been using it with GitProfile, that's my main purpose.

**Comment by arifszn** [comment]
Are you having the issue still? Dev.to has some issues with caching.

**Comment by arifszn** [comment]
Seems the issue is resolved.

![image](https://user-images.githubusercontent.com/45073703/218726776-cc59016f-f36d-42e7-8185-d81aefe52e25.png)
